### PR TITLE
Added HTTL, Rythm and Chunk template engines

### PR DESCRIPTION
**Pull request by vkuzel**
Hi,

I added HTTL and Rythm template engines and also updated version of Thymeleaf to version 3 beta which performs slightly better.

Please check it out.

### CODE REVIEW

**Comment by bckfnn** [comment]
Hi,

Are you sure that the Chunk implementation work for you?

When I tried your patch and I added a System.out.println(chunk.toString()) in Chunk.benchmark() I got the output (repeatedly):

```
[chtml template 'stocks.chunk' not found]<!-- looked in [templates\stocks.chunk.chtml] -->
```

The testcase seems to work fine and returns the expected output.

**Comment by vkuzel** [comment]
Hi Finn,

I've had few problems with Chunk templates but all of them should be solved for quite some time now. Tom (author of Chunk Templates) made few changes into his engine so latest version 3.2.0 should work fine. Please make sure that you are using last version of my patch (87075ce).

If you still have problems with it can you send me some more details? Maybe you can fork this project and then apply my patch so I can check it out.

Btw. my branch is here: https://github.com/vkuzel/template-benchmark

**Comment by bckfnn** [comment]
Hi Václav,

I have run your branch and get the same result. I changed the benchmark method in Chunk.java to 

```
@Benchmark
public String benchmark() {
    chunk.setMultiple(getContext());
    String r = chunk.toString();
    System.out.println(r);
    return r;
}
```

and the output I get when running the benchmark for Chunk is

```
[chtml template 'stocks.chunk' not found]<!-- looked in [templates\stocks.chunk.chtml] -->
```

I have tested on windows 10 with 

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

**Comment by vkuzel** [comment]
Hi Finn,

you are right. There is a problem with file separator on Windows. In Chunk templates there's a method that ensures that paths have trailing file separators. On Windows platform this method appends backslash to a path which causes problems.

@see https://github.com/tomj74/chunk-templates/blob/master/src/main/java/com/x5/util/Path.java#L11

I'll try to fix it and create a patch to Chunk templates over the weekend. If Tom accepts my patch and releases new version of Chunk templates I will update my fork of template-benchmark.

Stay tuned.

**Comment by vkuzel** [comment]
Hi Finn,

new version of Chunk Templates finally arrived so I fixed the code. Please check it out.

**Pull request closed without merging**
